@echo off
echo Initializing Git...
git init
echo Adding Remote...
git remote add origin https://github.com/Rahul-DS633/NetGurad-Ai.git
echo Setting Branch...
git branch -M main
echo Committing Files...
git add .
git commit -m "Initial commit of NetGuard AI"
echo Pushing to GitHub...
git push -u origin main
pause
